@startuml

' interface TasksContract
interface Presenter
interface View

class TasksPresenter
class TasksFragment
class Acvitity

' TasksContract *-- Presenter
' TasksContract *-- View

Acvitity *-- TasksPresenter
Acvitity *-- TasksFragment

Presenter *-- View
View *-- Presenter

Presenter <|-- TasksPresenter
View <|-- TasksFragment

@enduml